server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ipc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
netty:
  port: 20001
  listenEquipmentType: pcd01
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hcjc666.tcpserver.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.yml